services:
  container:
    security_opt:
      - no-new-privileges:true
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: lemon_webapp
    ports:
      - "22:22"
    volumes:
      - /home/user/data/PCAP-Dateien:/var/log/.journal
      - /home/user/data/Systemlogs:/var/log/auth
      - /home/user/data/Terminal-Recordings:/tmp/.systemd-private
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    logging:
      driver: "none"
    networks:
      - honeypot_net

networks:
  honeypot_net:
    driver: bridge
    name: br-honeypot
    driver_opts:
      com.docker.network.bridge.name: br-honeypot