# .github/workflows/devsecops.yml 
name: DevGuard DevSecOps

on:
    push:

permissions:
    contents: read
    packages: write

jobs:
    call-devsecops:
        uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
        with:
            asset-name: "l3montree-cybersecurity/projects/l3montree-intern/assets/ssh-cinema-fly-trap"
            api-url: "https://api.main.devguard.org"
            web-ui: "https://main.devguard.org"
        secrets:
            devguard-token: "${{ 71350e41535de33ae770489805f32cde6386f2b4bdf04540e188e0306d71aef4 }}" # you need to create this secret in your GitHub repository settings 
